In [1]:
import numpy as np

### 1D arrays of ones

In [2]:
arr=np.ones(5)
print(arr)
arr.dtype ##default array created by python is in float dtype

[1. 1. 1. 1. 1.]


dtype('float64')

In [3]:
arr=np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [66]:
np.ones((5,3), dtype=int) #2D array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [67]:
np.zeros((5,4), dtype=int) #2D array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### arange function

In [13]:
list(range(1,5))

[1, 2, 3, 4]

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [20]:
#np.arange(start,end,step)

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
np.random.randint(3,size=2) #upper bound=3 --> means the max no.of range of integers generated (n-1), size=total number of integers in the array

array([1, 0])

In [41]:
np.random.randint(5,size=5)

array([3, 1, 0, 2, 2])

In [43]:
#using upper and lower bound in random functio 
np.random.randint(1,5, size=7) #random numbers generated between 1 to 4

array([1, 2, 2, 4, 1, 4, 3])

### Create an array of first 10 multiples of 5 using the 'arange' function.

In [61]:
np.arange(5,55,5) #star,stop,step

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [65]:
np.random.random([1,5]) #random function is only for 2d array, floating values created

array([[0.24206245, 0.16125372, 0.13616657, 0.11431916, 0.34964486]])

#### array of evenly spaced numbers over a specified interval.