In [5]:
import numpy as np

In [9]:
mydata= np.genfromtxt('numpii.csv', delimiter =',', dtype='int', skip_header=1)
print(mydata)

[[101   1 745]
 [102   2 579]
 [103   5 976]
 [104   7 136]
 [105  12 355]
 [106  11 773]]
